      SUBROUTINE ODRPACK( FCN, N, NP, BETA, INFO, NFEV, CHISQR, ERR,
     &     LO, HI, Y, X, IPRINT, TOL, NDIGIT )

      USE ODRPACK95
      USE REAL_PRECISION

      INTERFACE
         SUBROUTINE FCN(N,M,NP,NQ,LDN,LDM,LDNP,BETA,XPLUSD,IFIXB,IFIXX,
     &        LDIFX,IDEVAL,F,FJACB,FJACD,ISTOP)
         USE REAL_PRECISION
         INTEGER :: IDEVAL,ISTOP,LDIFX,LDM,LDN,LDNP,M,N,NP,NQ
         REAL (KIND=R8) :: BETA(NP),F(LDN,NQ),FJACB(LDN,LDNP,NQ),
     &        FJACD(LDN,LDM,NQ),XPLUSD(LDN,M)
         INTEGER :: IFIXB(NP),IFIXX(LDIFX,M)
         END SUBROUTINE FCN
      END INTERFACE

      INTEGER N, NP, INFO, NFEV, IPRINT, NDIGIT
      REAL (KIND=R8) BETA(NP), ERR(NP), LO(NP), HI(NP), X(N,1), Y(N,1),
     &     TOL 
C DIWINF
      INTEGER
     &   BOUNDI,IDFI,INT2I,IPRINI,IRANKI,ISTOPI,JOBI,IFIX2I,LDTTI,
     &   LIWKMN,LUNERI,LUNRPI,MAXITI,MSGBI,MSGDI,NETAI,NFEVI,NITERI,
     &   NJEVI,NNZWI,NPPI,NROWI,NTOLI


C DWINF
      INTEGER
     &   ACTRSI,ALPHAI,BETACI,BETANI,BETASI,BETA0I,DELTAI,DELTNI,DELTSI,
     &   DIFFI,EPSI,EPSMAI,ETAI,FJACBI,FJACDI,FNI,FSI,LOWERI,
     &   LWKMN,OLMAVI,OMEGAI,PARTLI,PNORMI,PRERSI,QRAUXI,
     &   RCONDI,RNORSI,RVARI,SDI,SI,SSFI,SSI,SSTOLI,TAUFCI,TAUI,TI,TTI,
     &   UI,UPPERI,VCVI,WE1I,WRK1I,WRK2I,WRK3I,WRK4I,WRK5I,WRK6I,WRK7I,
     &   WSSI,WSSDEI,WSSEPI,XPLUSI
      LOGICAL ISODR

C  PARAMETER DECLARATIONS AND SPECIFICATIONS
      INTEGER    LIWORK,LWORK,J

      REAL (KIND=R8) WORK(:)
      INTEGER IWORK(:)
      POINTER        IWORK,WORK

      INTEGER M, NQ
      PARAMETER( M = 1, NQ = 1 )

      LWORK= 18+13*NP+NP**2+M+M**2+4*N*NQ+6*N*M+2*N*NQ*NP+
     &      2*N*NQ*M+NQ**2+5*NQ+NQ*(NP+M)+N*NQ*NQ
      LIWORK=20+2*NP+NQ*(NP+M)


      x = 0.0_R8
      y = 0.0_R8

      ALLOCATE( WORK(LWORK), IWORK(LIWORK))

      CALL ODR(FCN,N,M,NP,NQ,BETA,Y,X,NDIGIT=NDIGIT,
     &     SSTOL=TOL,PARTOL=TOL,IPRINT=IPRINT,
     &     WORK=WORK,IWORK=IWORK,INFO=INFO,LOWER=LO,UPPER=HI)


      CALL DIWINF(M,NP,NQ,MSGBI,MSGDI,IFIX2I,ISTOPI,NNZWI,NPPI,
     &     IDFI,JOBI,IPRINI,LUNERI,LUNRPI,NROWI,NTOLI,NETAI,MAXITI,
     &     NITERI,NFEVI,NJEVI,INT2I,IRANKI,LDTTI,BOUNDI,LIWKMN)

      CALL DWINF
     &   (N,M,NP,NQ,LDWE,LD2WE,ISODR,
     &   DELTAI,EPSI,XPLUSI,FNI,SDI,VCVI,
     &   RVARI,WSSI,WSSDEI,WSSEPI,RCONDI,ETAI,
     &   OLMAVI,TAUI,ALPHAI,ACTRSI,PNORMI,RNORSI,PRERSI,
     &   PARTLI,SSTOLI,TAUFCI,EPSMAI,
     &   BETA0I,BETACI,BETASI,BETANI,SI,SSI,SSFI,QRAUXI,UI,
     &   FSI,FJACBI,WE1I,DIFFI,
     &   DELTSI,DELTNI,TI,TTI,OMEGAI,FJACDI,
     &   WRK1I,WRK2I,WRK3I,WRK4I,WRK5I,WRK6I,WRK7I,
     &   LOWERI,UPPERI,
     &   LWKMN)

      NFEV = IWORK( NFEVI )
      CHISQR =  WORK( WSSI )
      SDI = 2 * N * M + 2 * N + 1
      DO J = 1, NP
         ERR( J ) = WORK( SDI - 1 + J )
      END DO

      DEALLOCATE(WORK,IWORK)
      return
      END
