#
#  Copyright (C) 2007, 2018, 2022
#  Smithsonian Astrophysical Observatory
#
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

"""Create a session for modeling and fitting data.

Provide access to the functionality of the `sherpa.ui.utils.Session`
class, hiding the access to the Sesson object.

What models are supported?
==========================

The session includes support for models defined in
`sherpa.models.basic`, `sherpa.models.template`, and
`sherpa.instrument`.

What symbols are exported?
==========================

A number of routines from `sherpa.utils` and data classes from
`sherpa.data` are re-exported by this module, but most are taken from
the list generated by `sherpa.ui.utils.Session._export_names` when
applied to the output of ``globals()``.

Example
=======

>>> from sherpa import ui
>>> ui.load_arrays(1, [10, 14, 20], [2, 6, 15])
>>> ui.set_source(ui.polynom1d.mdl)
>>> mdl.c1.thaw()
>>> ui.set_stat("leastsq")
>>> ui.fit()
Dataset               = 1
Method                = levmar
Statistic             = leastsq
Initial fit statistic = 222
Final fit statistic   = 0.947368 at function evaluation 6
Data points           = 3
Degrees of freedom    = 1
Change in statistic   = 221.053
   mdl.c0         -11.6316     +/- 2.13985
   mdl.c1         1.31579      +/- 0.140488
>>> ui.plot_resid()
WARNING: The displayed errorbars have been supplied with the data or calculated using chi2xspecvar; the errors are not used in fits with leastsq

"""

# pylint: disable=protected-access

import sherpa.all
import sherpa.ui.utils
from sherpa.utils import calc_mlr, calc_ftest, rebin, histogram1d, \
    histogram2d, gamma, lgam, igamc, igam, incbet, multinormal_pdf, \
    multit_pdf
from sherpa.data import Data1D, Data1DInt, Data2D, Data2DInt
from sherpa.logposterior import Prior

# We build up __all__ as we go along
__all__ = ['calc_mlr', 'calc_ftest', 'Data1D', 'Data1DInt',
           'Data2D', 'Data2DInt', 'rebin', 'histogram1d',
           'histogram2d', 'gamma', 'lgam', 'igamc',
           'igam', 'incbet', 'Prior', 'multinormal_pdf', 'multit_pdf']

_session = utils.Session()
_session._add_model_types(sherpa.models.basic)
_session._add_model_types(sherpa.models.template)
# To get PSFModel in list of models -- doesn't inherit from ArithmeticModel
_session._add_model_types(sherpa.instrument, baselist=(sherpa.models.Model,))

__all__.extend(_session._export_names(globals()))

__all__ = tuple(__all__)
