name: sherpa

channels:
  - conda-forge
  - astropy
  - nodefaults

dependencies:
  - bison
  - python=3.13
  - numpy
  - pandoc
  - matplotlib
  - astropy
  - pip
  - graphviz
  - sphinx>=5.0
  - pip:
    - ipykernel
    - nbsphinx
    - sphinx-astropy
    - sphinx_rtd_theme>=3.0.0
    - bokeh
    - arviz<1.0.0
    - optimagic
